### ISSUE TITLE
Change all ints used for karma levels to int64

### ISSUE THREAD

**Issue by connorkuehl** [connorkuehl/popple#100]
The database schema already generates 64-bit ints, but all of the `map[string]int` or `adapter.LeaderboardEntry` don't. These instances should be updated to use int64 instead of int.

**Comment by RishiKumarRay** [comment]
We have to simply change int references to int64?

**Comment by connorkuehl** [comment]
Most of them, yeah. Only if it has to do with storing someone's karma. The `map[string]int` types can be safely changed to `map[string]int64`.

**Comment by RishiKumarRay** [comment]
Assign it to me then I would like to do

**Comment by connorkuehl** [comment]
Thanks! Let me know if I can be of any help 🙂

**Comment by RishiKumarRay** [comment]
@connorkuehl please review the PR #103

**Comment by connorkuehl** [comment]
Obsoleted by commit 033633a8f9254f172e740e5d48dd733c5bfbcb6b
