### ISSUE TITLE
Add a version subcommand 

### ISSUE THREAD

**Issue by connorkuehl** [connorkuehl/popple#14]
This way, people can ask the bot what version it is.

I.e., `@Popple version`

```
Persion) @Popple version
Popple) 1.0.0
```

**Comment by pradeepnnv** [comment]
I would like to try this issue.

**Comment by connorkuehl** [comment]
Thanks, @pradeepnnv! Let me know if I can be of assistance.

**Comment by connorkuehl** [comment]
Hi @pradeepnnv, just wanted to check in on this. Is this something you'd still like to work on? Is there anything I can do to help?

**Comment by connorkuehl** [comment]
No worries! I was just checking in, I'm in no rush. 

I'm not familiar with Cobra, but at first glance it seems like it may be more complicated that we need.

I was thinking that we could just add a file, `version.go`, that exports a constant that corresponds to the source code version. As of right now, it'd be 1.1.0. I'll have to remember to update this version whenever I tag a new release.

Then you could add a function to `command.go` that submits a reply to the discord channel, using that version string.

This can all be wired up in the [command dispatch table](https://github.com/connorkuehl/popple/blob/master/job.go#L22) in command.go.

Does that seem reasonable?

**Comment by pradeepnnv** [comment]
Sure. Thanks. 

I definitely appreciate the feedback. Let me create this and submit a PR.

**Comment by pradeepnnv** [comment]
@connorkuehl, submitted https://github.com/connorkuehl/popple/pull/15.

Please review.

**Comment by connorkuehl** [comment]
Closed by 4137d2f87f4b0b8da12671a2044388290dba8d9f.
