### ISSUE TITLE
Include version in startup message in func main

### ISSUE THREAD

**Issue by connorkuehl** [connorkuehl/popple#19]

**Comment by rojanDinc** [comment]
Hi can I get assigned to this? Id like to contribute.

**Comment by connorkuehl** [comment]
Sure, @rojanDinc! Thanks! Let me know if I can help in any way. 🙂

**Comment by connorkuehl** [comment]
Fixed by 4c18f0fe1036582d90d334d75eaaadf14aaab6bd
