### ISSUE TITLE
Switch "deadline" command line argument from uint to time.Duration

### ISSUE THREAD

**Issue by connorkuehl** [connorkuehl/popple#42]
Right now, the "deadline" flag is a uint and converted to a Duration later on.

```go
    timeout := flag.Uint("deadline", 3, "seconds to wait for workers to exit when shutting down")
```

It looks like the flag package supports Duration types out of the box (rest of output omitted for brevity)

```console
$ go doc flag
func Duration(name string, value time.Duration, usage string) *time.Duration
```

Change it.

**Comment by krishnaindani** [comment]
Hey, Would like to see if I can work on this? I would like to try.

**Comment by connorkuehl** [comment]
Sure, thanks! Let me know if I can help in any way.

**Comment by krishnaindani** [comment]
Sure. Thank you.

**Comment by krishnaindani** [comment]
Let me know what do you think https://github.com/connorkuehl/popple/pull/44
