### ISSUE TITLE
Clean up the shutdown logic in cmd/discord/popple/main.go

### ISSUE THREAD

**Issue by connorkuehl** [connorkuehl/popple#83]
The worker shutdown is kind of onerous. Instead of tracking how many workers have returned, use a sync.WaitGroup instead.

However, it's not sufficient to just wait for `wg.Done()` since that will prevent us from quitting even if the deadline has passed, so you might consider something like:

```go
    workersDone := make(chan struct{})
    go func() {
        wg.Wait()
        close(workersDone)
    }()
    
    select {
        case <- deadline:
            // emit warning blah
        case <- workersDone:
            // emit that all workers are done
    }
```

**Comment by willmadison** [comment]
Taking a look...

**Comment by connorkuehl** [comment]
Thanks! Please don’t hesitate to send me questions as they arise.
